name: Go nightly build
on:
  workflow_dispatch:
  schedule:
    - cron: "6 10 * * *"
jobs:
  test_client:
    runs-on: ${{ matrix.os }}
    name: Run tests of master on ${{ matrix.os }} with Go ${{ matrix.go_version }}
    strategy:
        matrix:
            os: [ ubuntu-latest, windows-latest ]
            go_version: [ 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18 ]
        fail-fast: false
    steps:     
    
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
          
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Test
        run: |
          ./rc.sh start
          env MEMBER_COUNT=3 make test-cover
